name: MCPanelBackend
main: cn.apisium.mcpanelbackend.Main
version: 1.0
description: MC panel
author: Shirasawa
website: https://apisium.cn
depend:
  - NekoEssentials
commands:
  panel:
    permission: neko.panel
permissions:
  neko.panel:
    default: 'true'
api-version: '1.13'
